title: Jagadeeswar Puli
logo: /assets/img/WhatsApp Image 2023-02-01 at 7.08.45 PM.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
